# Generated by Django 5.0.1 on 2026-01-30 07:02

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(default='fa-folder', max_length=50, verbose_name='İkon')),
                ('color', models.CharField(default='#007bff', max_length=20, verbose_name='Renk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='documents.documentcategory', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Doküman Kategorisi',
                'verbose_name_plural': 'Doküman Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, verbose_name='Dosya')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('txt', 'Text'), ('md', 'Markdown')], max_length=10, verbose_name='Dosya Türü')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Dosya Boyutu (bytes)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Etiketler')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata')], default='pending', max_length=20, verbose_name='Durum')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='Chunk Sayısı')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('is_public', models.BooleanField(default=False, verbose_name='Herkese Açık')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlenme Tarihi')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Doküman',
                'verbose_name_plural': 'Dokümanlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(verbose_name='Sıra')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='Token Sayısı')),
                ('vector_id', models.CharField(blank=True, max_length=100, verbose_name='Vector ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sayfa No')),
                ('section', models.CharField(blank=True, max_length=200, verbose_name='Bölüm')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document', verbose_name='Doküman')),
            ],
            options={
                'verbose_name': 'Doküman Parçası',
                'verbose_name_plural': 'Doküman Parçaları',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
