# Generated by Django 5.0.1 on 2026-01-30 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sohbet',
                'verbose_name_plural': 'Sohbetler',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Kullanıcı'), ('assistant', 'Asistan'), ('system', 'Sistem')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='Kaynaklar')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Güven Skoru')),
                ('is_helpful', models.BooleanField(blank=True, null=True, verbose_name='Yararlı mı?')),
                ('feedback', models.TextField(blank=True, verbose_name='Geri Bildirim')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Token Kullanımı')),
                ('response_time_ms', models.PositiveIntegerField(default=0, verbose_name='Yanıt Süresi (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Sohbet')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['created_at'],
            },
        ),
    ]
